#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_DEPLOY_ROOT="$REPO_ROOT/.deploy"
DEFAULT_SKILLS_DIR="${CODEX_HOME:-$HOME/.codex}/skills"
DEFAULT_PERSISTENT_ROOT="${S2F_PERSISTENT_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/s2f-skills}"
CORE_STACKS=("alphagenome" "gpn" "nt-jax")

usage() {
  cat <<'EOF'
Usage: bootstrap.sh [options]

One-step installer for a fresh machine. By default, it:
  1. Links all packaged skills into the Codex skills directory
  2. Provisions the core software stacks: alphagenome, gpn, nt-jax
  3. Runs the repository smoke test against the deployed paths

Options:
  --deploy-root DIR      Working root for virtual environments and upstream clones.
                         Default: <repo>/.deploy
  --persistent-root DIR  Use a persistent runtime root for long-lived environments/caches.
                         Implies deploy root: <persistent-root>/deploy
                         Default persistent root when set: ${XDG_CACHE_HOME:-$HOME/.cache}/s2f-skills
  --write-env-file FILE  Write reusable environment exports (cache paths + deploy root).
                         Default when --persistent-root is set: <persistent-root>/env.sh
  --skills-dir DIR       Destination Codex skills directory.
                         Default: ${CODEX_HOME:-$HOME/.codex}/skills
  --python BIN           Python executable to use for venv creation. Default: python3
  --copy-skills          Copy skills instead of symlinking them.
  --force-links          Replace existing paths in the skills directory.
  --with-evo2-light      Also provision evo2-light and include it in smoke tests.
  --with-evo2-full       Also provision evo2-full in the currently active conda env.
  --with-ntv3-hf         Also provision ntv3-hf and include it in smoke tests.
  --with-borzoi          Also provision borzoi and include it in smoke tests.
  --prefetch-models      Prefetch common Hugging Face model checkpoints to local cache.
  --prefetch-model ID    Add one extra Hugging Face model id to prefetch (repeatable).
  --hf-token TOKEN       Hugging Face token for gated/private model prefetch.
  --skip-link            Skip linking/copying skills.
  --skip-smoke           Skip the final smoke test.
  -h, --help             Show this help message.

Environment variables:
  JAX_INSTALL_CMD        Optional hardware-specific JAX install command for nt-jax.
  TORCH_INSTALL_CMD      Required when using --with-evo2-light.
EOF
}

deploy_root="$DEFAULT_DEPLOY_ROOT"
skills_dir="$DEFAULT_SKILLS_DIR"
python_bin="python3"
deploy_root_explicit=0
persistent_root=""
write_env_file=""
copy_skills=0
force_links=0
with_evo2_light=0
with_evo2_full=0
with_ntv3_hf=0
with_borzoi=0
prefetch_models=0
hf_token="${HF_TOKEN:-${HUGGINGFACE_HUB_TOKEN:-}}"
prefetch_extra_models=()
skip_link=0
skip_smoke=0

write_runtime_env_file() {
  local env_file="$1"
  mkdir -p "$(dirname "$env_file")"
  {
    printf '# Generated by scripts/bootstrap.sh on %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'export S2F_ENV_FILE="%s"\n' "$env_file"
    if [[ -n "$persistent_root" ]]; then
      printf 'export S2F_PERSISTENT_ROOT="%s"\n' "$persistent_root"
    fi
    printf 'export S2F_DEPLOY_ROOT="%s"\n' "$deploy_root"
    if [[ -n "${XDG_CACHE_HOME:-}" ]]; then
      printf 'export XDG_CACHE_HOME="%s"\n' "$XDG_CACHE_HOME"
    fi
    if [[ -n "${HF_HOME:-}" ]]; then
      printf 'export HF_HOME="%s"\n' "$HF_HOME"
    fi
    if [[ -n "${HUGGINGFACE_HUB_CACHE:-}" ]]; then
      printf 'export HUGGINGFACE_HUB_CACHE="%s"\n' "$HUGGINGFACE_HUB_CACHE"
    fi
    if [[ -n "${TRANSFORMERS_CACHE:-}" ]]; then
      printf 'export TRANSFORMERS_CACHE="%s"\n' "$TRANSFORMERS_CACHE"
    fi
    if [[ -n "${TORCH_HOME:-}" ]]; then
      printf 'export TORCH_HOME="%s"\n' "$TORCH_HOME"
    fi
    if [[ -n "${PIP_CACHE_DIR:-}" ]]; then
      printf 'export PIP_CACHE_DIR="%s"\n' "$PIP_CACHE_DIR"
    fi
  } > "$env_file"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deploy-root)
      deploy_root="$2"
      deploy_root_explicit=1
      shift 2
      ;;
    --persistent-root)
      persistent_root="$2"
      shift 2
      ;;
    --write-env-file)
      write_env_file="$2"
      shift 2
      ;;
    --skills-dir)
      skills_dir="$2"
      shift 2
      ;;
    --python)
      python_bin="$2"
      shift 2
      ;;
    --copy-skills)
      copy_skills=1
      shift
      ;;
    --force-links)
      force_links=1
      shift
      ;;
    --with-evo2-light)
      with_evo2_light=1
      shift
      ;;
    --with-evo2-full)
      with_evo2_full=1
      shift
      ;;
    --with-ntv3-hf)
      with_ntv3_hf=1
      shift
      ;;
    --with-borzoi)
      with_borzoi=1
      shift
      ;;
    --prefetch-models)
      prefetch_models=1
      shift
      ;;
    --prefetch-model)
      prefetch_models=1
      prefetch_extra_models+=("$2")
      shift 2
      ;;
    --hf-token)
      hf_token="$2"
      shift 2
      ;;
    --skip-link)
      skip_link=1
      shift
      ;;
    --skip-smoke)
      skip_smoke=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unexpected argument '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$with_evo2_light" -eq 1 && "$with_evo2_full" -eq 1 ]]; then
  echo "error: choose either --with-evo2-light or --with-evo2-full, not both" >&2
  exit 1
fi

if [[ -n "$persistent_root" && "$deploy_root_explicit" -eq 1 ]]; then
  echo "error: use either --deploy-root or --persistent-root, not both" >&2
  exit 1
fi

if [[ -n "$persistent_root" ]]; then
  deploy_root="${persistent_root%/}/deploy"
  if [[ -z "$write_env_file" ]]; then
    write_env_file="${persistent_root%/}/env.sh"
  fi
  cache_root="${persistent_root%/}/cache"
  export XDG_CACHE_HOME="$cache_root/xdg"
  export HF_HOME="$cache_root/huggingface"
  export HUGGINGFACE_HUB_CACHE="$HF_HOME/hub"
  export TRANSFORMERS_CACHE="$HF_HOME/transformers"
  export TORCH_HOME="$cache_root/torch"
  export PIP_CACHE_DIR="$cache_root/pip"
  mkdir -p \
    "$deploy_root" \
    "$XDG_CACHE_HOME" \
    "$HF_HOME" \
    "$HUGGINGFACE_HUB_CACHE" \
    "$TRANSFORMERS_CACHE" \
    "$TORCH_HOME" \
    "$PIP_CACHE_DIR"
fi

if [[ -n "$write_env_file" ]]; then
  write_runtime_env_file "$write_env_file"
fi

if [[ "$skip_link" -ne 1 ]]; then
  link_args=(--skills-dir "$skills_dir")
  if [[ "$copy_skills" -eq 1 ]]; then
    link_args+=(--copy)
  fi
  if [[ "$force_links" -eq 1 ]]; then
    link_args+=(--force)
  fi
  bash "$REPO_ROOT/scripts/link_skills.sh" "${link_args[@]}"
fi

for stack in "${CORE_STACKS[@]}"; do
  bash "$REPO_ROOT/scripts/provision_stack.sh" "$stack" \
    --deploy-root "$deploy_root" \
    --python "$python_bin"
done

evo2_python=""
if [[ "$with_evo2_light" -eq 1 ]]; then
  bash "$REPO_ROOT/scripts/provision_stack.sh" evo2-light \
    --deploy-root "$deploy_root" \
    --python "$python_bin"
  evo2_python="$deploy_root/venvs/evo2-light/bin/python"
fi

if [[ "$with_evo2_full" -eq 1 ]]; then
  bash "$REPO_ROOT/scripts/provision_stack.sh" evo2-full \
    --deploy-root "$deploy_root" \
    --python "$python_bin"
  evo2_python="python"
fi

ntv3_python=""
if [[ "$with_ntv3_hf" -eq 1 ]]; then
  bash "$REPO_ROOT/scripts/provision_stack.sh" ntv3-hf \
    --deploy-root "$deploy_root" \
    --python "$python_bin"
  ntv3_python="$deploy_root/venvs/ntv3-hf/bin/python"
fi

borzoi_python=""
if [[ "$with_borzoi" -eq 1 ]]; then
  bash "$REPO_ROOT/scripts/provision_stack.sh" borzoi \
    --deploy-root "$deploy_root" \
    --python "$python_bin"
  borzoi_python="$deploy_root/venvs/borzoi/bin/python"
fi

if [[ "$prefetch_models" -eq 1 ]]; then
  prefetch_args=(--deploy-root "$deploy_root" --python "$python_bin")
  if [[ -n "$hf_token" ]]; then
    prefetch_args+=(--hf-token "$hf_token")
  fi
  for model_id in "${prefetch_extra_models[@]}"; do
    prefetch_args+=(--model "$model_id")
  done
  bash "$REPO_ROOT/scripts/prefetch_models.sh" "${prefetch_args[@]}"
fi

if [[ "$skip_smoke" -ne 1 ]]; then
  smoke_args=(--skills-dir "$skills_dir")
  smoke_args+=(--alphagenome-python "$deploy_root/venvs/alphagenome/bin/python")
  smoke_args+=(--gpn-python "$deploy_root/venvs/gpn/bin/python")
  smoke_args+=(--nt-python "$deploy_root/venvs/nt-jax/bin/python")
  if [[ -n "$ntv3_python" ]]; then
    smoke_args+=(--ntv3-python "$ntv3_python")
  fi
  if [[ -n "$borzoi_python" ]]; then
    smoke_args+=(--borzoi-python "$borzoi_python")
  fi
  if [[ -n "$evo2_python" ]]; then
    smoke_args+=(--evo2-python "$evo2_python")
  fi
  bash "$REPO_ROOT/scripts/smoke_test.sh" "${smoke_args[@]}"
fi

if [[ -n "$write_env_file" ]]; then
  echo "runtime env file written: $write_env_file"
  echo "tip: source \"$write_env_file\" in new shells to reuse the same caches and deploy paths."
fi

echo "bootstrap complete"
